use VALUE for argument types and then cast
This avoids an error from GCC 14 and clang 16 about function pointer
type mismatches, because they want the argument type to be VALUE.

    unicode.c:1039:20: error: passing argument 1 of ‘rb_ensure’ from incompatible pointer type [-Wincompatible-pointer-types]
    unicode.c:1057:20: error: passing argument 1 of ‘rb_ensure’ from incompatible pointer type [-Wincompatible-pointer-types]
    unicode.c:1058:20: error: passing argument 3 of ‘rb_ensure’ from incompatible pointer type [-Wincompatible-pointer-types]
    unicode.c:1227:20: error: passing argument 1 of ‘rb_ensure’ from incompatible pointer type [-Wincompatible-pointer-types]
    unicode.c:1228:20: error: passing argument 3 of ‘rb_ensure’ from incompatible pointer type [-Wincompatible-pointer-types]